Zaimportowanie funkcji i bibliotek.

In [ ]:
import numpy as np
from keras import Sequential
from keras.layers import Dense
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import OneHotEncoder

Wczytanie danych z pliku .csv i przeszkałcenie na numpy array.

In [2]:
dane = pd.read_csv(R'/content/drive/MyDrive/texture_samples.csv',index_col=0).to_numpy()
print(dane.shape)
print(dane)

(10752, 73)
[[3.36737205e-01 3.36737205e-01 4.11494823e-01 ... 4.06929871e-02
  4.80608932e-02 1.00000000e+00]
 [4.66596949e-01 4.66596949e-01 5.42439085e-01 ... 2.59013804e-02
  3.03419400e-02 1.00000000e+00]
 [8.20927657e-01 8.20927657e-01 9.16051832e-01 ... 1.24005115e-02
  1.53228385e-02 1.00000000e+00]
 ...
 [2.70047982e+00 2.70047982e+00 3.57870916e+00 ... 6.39942135e-04
  7.10401840e-04 4.00000000e+00]
 [3.22213337e+00 3.22213337e+00 4.08339017e+00 ... 5.97086450e-04
  6.56369167e-04 4.00000000e+00]
 [3.56077756e+00 3.56077756e+00 4.57058714e+00 ... 5.13980597e-04
  5.70952744e-04 4.00000000e+00]]


Podział danych na wektory cech oraz etykiety.

In [3]:
X = dane[:,:-1]
Y = dane[:,-1]
y_int = Y.astype(int)

Zmiana typu danych etykiet na int. Przekształcenie etykiet na OneHot - każda klasa w osobnej kolumnie.

In [4]:
onehotenc = OneHotEncoder(sparse_output=False)
y_onehot = onehotenc.fit_transform(y_int.reshape(-1, 1))
print(y_onehot)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


Podział danych na treningowe i testowe.

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y_onehot, test_size=0.3)

Utworzenie modelu sieci neuronowej, dodanie warstw, kompliacja modelu z odpowiednią funkcją straty i modelem optymalizacji. Uruchomienie uczenia.

In [ ]:
# Utwórz model
model = Sequential()

# Dodaj warstwy modelu
model.add(Dense(10, activation='sigmoid', input_dim=72)) #pierwsza warstwa
model.add(Dense(4, activation='softmax')) #druga warstwa

# Skompiluj model, używając miary dokładności
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

# Trenuj model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100, batch_size=10, shuffle=True)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/100
753/753 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.5400 - loss: 1.0853 - val_accuracy: 0.8571 - val_loss: 0.6184
Epoch 2/100
753/753 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8613 - loss: 0.5562 - val_accuracy: 0.9290 - val_loss: 0.4192
Epoch 3/100
753/753 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9040 - loss: 0.4131 - val_accuracy: 0.9619 - val_loss: 0.3409
Epoch 4/100
753/753 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.9070 - loss: 0.3507 - val_accuracy: 0.9656 - val_loss: 0.2944
Epoch 5/100
753/753 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9308 - loss: 0.2962 - val_accuracy: 0.9678 - val_loss: 0.2164
Epoch 6/100
753/753 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9478 - loss: 0.2401 - val_accuracy: 0.8524 - val_loss: 0.3655
Epoch 7/100
753/753 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9289 - loss: 0.2435 - val_accuracy: 0.9727 - val_loss: 0.1522
Epoch 8/100
753/753 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9232 - loss: 0.2482 - val_accu

Wykonanie predykcji na nauczonym modelu. Porównanie wyników z poprawnym przypisaniem do klas za pomocą macierzy pomyłek.

In [7]:
y_pred = model.predict(X_test)
y_pred_int = np.argmax(y_pred, axis=1)
y_test_int = np.argmax(y_test, axis=1)
cm = confusion_matrix(y_test_int, y_pred_int)
print(cm)

101/101 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
[[809   0   6   0]
 [  2 766   0  20]
 [ 11   0 804   0]
 [  0  14   0 794]]
